In [2]:
import numpy as np 

In [3]:
m = [[10,20,30,40], [50,60,70,80]]
b = np.array(m)
print(b)

[[10 20 30 40]
 [50 60 70 80]]


In [5]:
m =np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
m[1:2,2:3]

array([[7]])

In [21]:
m[2:3,4:5]

array([[14]])

In [26]:
m[1:2,1:3]

array([[6, 7]])

In [29]:
m[1:3,2:3]

array([[ 7],
       [12]])

In [42]:
 m[:2,3:5]

array([[3, 4],
       [8, 9]])

In [45]:
f= np.array(range(15),float)
f

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [46]:
f[f % 3 ==0]

array([ 0.,  3.,  6.,  9., 12.])

In [48]:
f[f % 4 ==1]

array([ 1.,  5.,  9., 13.])

In [74]:
np.eye(5,5,-1)*3 + np.eye(5,5)*2 + np.eye(5,5,1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [86]:
m = np.random.randint(0,11,(5,6))
m

array([[ 1,  5, 10,  3,  5,  7],
       [ 1,  2, 10,  9,  9,  1],
       [ 6,  0,  9,  0,  0,  3],
       [10,  3, 10,  0,  0,  1],
       [ 2,  1,  7,  2,  2,  5]])

In [88]:
np.max(m)

10

In [89]:
m.sum(axis=1)

array([31, 32, 18, 24, 19])

In [94]:
np.max(m.sum(axis=1))

32

In [91]:
m.mean(axis=0)

array([4. , 2.2, 9.2, 2.8, 3.2, 3.4])

In [92]:
np.min(m.mean(axis=0))

2.2

In [97]:
np.random.normal(10000,1,250)

array([ 9998.69647215, 10000.24785454, 10001.27885309,  9999.7816524 ,
        9998.97606743,  9997.17046645,  9999.84604227,  9998.21658498,
        9998.85782465,  9998.86903787,  9999.54074519,  9999.71622887,
       10000.57664193, 10000.41408927, 10000.50035834, 10001.28129567,
       10000.08568738,  9998.688898  ,  9999.9397449 ,  9999.31386604,
       10000.06052509,  9998.23691386, 10002.00873489,  9997.24110077,
       10000.99344394,  9999.40861513, 10001.0554238 , 10001.02420873,
       10000.07393384,  9999.32576099,  9999.55506046,  9999.6253577 ,
       10000.18558268,  9998.61439437,  9998.03375653,  9999.42526263,
       10000.197954  , 10001.3486531 ,  9999.44431754, 10000.44772666,
        9999.37276636,  9999.71786195,  9999.0634886 , 10001.52928569,
       10001.43068976,  9998.37491978, 10000.57499879, 10001.6274348 ,
        9999.2067878 ,  9998.81584529, 10000.93270723,  9999.27767324,
        9999.66338993, 10000.00650723,  9999.43567963,  9999.30655125,
      